### ISSUE TITLE
Unneeded space trying to restore

### ISSUE THREAD

**Issue by makorne** [tarantool/dump#10]
Пройдя ошибку описанную [https://github.com/tarantool/dump/issues/9](url)
наткнулся на `Duplicate key exists in unique index 'user' in space 'auth_oauth_app'`

Но восстанавливается вовсе не этот спейс! 
В директории только дамп другого спейса, все остальные остались в другой виртуалке.
Спейс auth_oauth_app вообще пустой в сдампленной базе, а восстанавливаемый - почти гигабайт

По описанию, если в восстанавливаемой директории только дамп одного спейса, то восстанавливается только он. Но дебаглог показывает:
`Reading contents of /home/den/tnt-temps/back/

Found 1 files

Started restoring space auth_oauth_app
`
Почему восстанавливается auth_oauth_app?? 
Поиск внутри дампа по слову "oauth" ничего не нашел
Может это название ошибочно берется из создаваемого в процессе модулем authman?

Или может это связано с тем что дампил ТТ1.9, а восстанавливается на 1.10.2-149?

**Comment by kostja** [comment]
Пожалуйста напишите что вы делали, а не только что у вас получилось.

**Comment by makorne** [comment]
В двух виртуалках почти идентичные приложения, в обоих используется модуль authman, разница только в разной версии ТТ 1.9 и 1.10, размер одного спейса,  и индексы.

Чтобы перенести с 1.9 на 1.10, сдампил
`require('dump').dump('/path/to/logical/backup')`

Перенес только один файл 520.dump, с нужными данными
В 1.10 выполняю
`require('dump').restore('/path/to/logical/backup')`

Дебаглог показывает:

`Reading contents of /home/den/tnt-temps/back/

Found 1 files

Started restoring space auth_oauth_app
`
Почему восстанавливается auth_oauth_app?? Внутри дампа  слова oauth не находит.

**Comment by alyapunov** [comment]
* makorne <notifications@github.com> [19/03/07 19:41]:
> В двух виртуалках почти идентичные приложения, в обоих используется модуль authman, разница только в разной версии ТТ 1.9 и 1.10, размер одного спейса,  и индексы.
> 
> Чтобы перенести с 1.9 на 1.10, сдампил
> `require('dump').dump('/path/to/logical/backup')`
> 
> Перенес только один файл 520.dump, с нужными данными
> В 1.10 выполняю
> `require('dump').restore('/path/to/logical/backup')`
> 
> Дебаглог показывает:
> 
> `Reading contents of /home/den/tnt-temps/back/
> 
> Found 1 files
> 
> Started restoring space auth_oauth_app
> `
> Почему восстанавливается auth_oauth_app?? Внутри дампа  слова oauth не находит.

В файле 520.dump содержатся данные 520 спейса. Метаданные (CREATE
SPACE) содержится в дампе системного спейса _space. Ваша ошибка в
том, что вы перенесли дамп данных, но никак не восстановили
метаданные. auth_oauth_app это, видимо, имя спейса которое у вас
уже содержится на destination server.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tarantool/dump/issues/10#issuecomment-470599956

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.io - www.twitter.com/kostja_osipov

**Comment by makorne** [comment]
Я действовал точно по инструкции с главной страницы:

`If you want to restore only a single space, restore from a directory which contains its dump file and nothing else. The dump skips spaces with id < 512 (the system spaces), with the exception of tuples which contain metadata of user-defined spaces, to ensure smooth restore on an empty instance. If you want to restore data into an existing space, delete files with ids < 512 from the dump directory.`

Может быть она неполна?

**Comment by kostja** [comment]
Обновил документацию.
