### ISSUE TITLE
Не информирует о ошибке

### ISSUE THREAD

**Issue by makorne** [tarantool/dump#9]
Сдампил гигабайтный спейс, и пытаюсь восстановить, на чистый инстанс один спейс 520.dump

Процедура проходит без ошибок, но по времени очевидно что ничего не восстановлено.

Включив же дебаг-лог,  оказывается что критическая ошибка.
` Reading contents of /home/den/tnt-temps/back/
 Found 1 files
SystemError at /build/tarantool-1.10.2.149/src/lua/fio.c:53`

Если  спейс маленький, то можно и не заметить что ничего не восстановилось, поэтому хорошо бы  информировать о успешности процесса.

**Comment by kostja** [comment]
Модуль не бросает исключений. Вы проверяете возвращаемое значение?

**Comment by makorne** [comment]
Нет, не проверяю, да и в вашем примере не предполагается 
`require('dump').restore('/path/to/logical/backup')`

Включил в box.cfg log_level=7
Прочитал ошибку в этом логе.

С ошибкой-то разобрался - права на директорию недостаточны были, но все равно хоть какое-то информирование о успешности процесса уже давно везде норма...

**Comment by alyapunov** [comment]
* makorne <notifications@github.com> [19/03/07 19:31]:
> Нет, не проверяю, да и в вашем примере не предполагается 
> `require('dump').restore('/path/to/logical/backup')`
> 
> Включил в box.cfg log_level=7
> Прочитал ошибку в этом логе.
> 
> С ошибкой-то разобрался - права на директорию недостаточны были, но все равно хоть какое-то информирование о успешности процесса уже давно везде норма...

Ошибка содержится в возвращаемом значении функции restore().

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.io - www.twitter.com/kostja_osipov

**Comment by makorne** [comment]
Тогда получается что приведенный на главной странице пример использования  дезинформирует, приводя к потере этого функционала.
`require('dump').restore('/path/to/logical/backup')`
Наверное стоит дополнить с вариантом получения  информации о ошибках.
Спасибо!

**Comment by kostja** [comment]
Обновил readme.
